container:
  image: node:10

lint_task:
  install_script: npm install
  test_script: npm run lint

publish_task:
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - lint
  environment:
    GITHUB_TOKEN: ENCRYPTED[1bbc6f242e440f8b230be98dede45c83acdb44d67cb92da704d36778342cf03250860663fd33b74294d457e11ac1eacb]
    NPM_TOKEN: ENCRYPTED[def622d020125e68de145ab1524d81be9e848fb62ef06319f5a419fc1b968cf213e63e28e6827169f4a97a5807a7df0c]
  script:
    - npm install
    - npx semantic-release
