---
release_tags: &release_tags
  tags:
    only: /^v\d+(\.\d+){2}(-.*)?$/

# "Include" for unit tests definition.
unit_tests: &unit_tests
  steps:
    - checkout
    - run: npm install
    - run: npm run compile
    - run: npm run test-only
    - run: npm run codecov

version: 2.0
workflows:
  version: 2
  tests:
    jobs: &workflow_jobs
      - node6:
          filters: *release_tags
      - node8:
          filters: *release_tags
      - node10:
          filters: *release_tags
      - lint:
          requires:
            - node6
            - node8
            - node10
          filters: *release_tags
      - publish_npm:
          requires:
            - node6
            - node8
            - node10
          filters:
            branches:
              ignore: /.*/
            <<: *release_tags
  nightly:
    triggers:
      - schedule:
          cron: 0 7 * * *
          filters:
            branches:
              only: master
    jobs: *workflow_jobs

jobs:
  node6:
    docker:
      - image: node:6
        user: node
    <<: *unit_tests
  node8:
    docker:
      - image: node:8
        user: node
    <<: *unit_tests
  node10:
    docker:
      - image: node:10
        user: node
    <<: *unit_tests
  lint:
    docker:
      - image: node:10
        user: node
    steps:
      - checkout
      - run: npm install
      - run: npm run check && npm run license-check

  publish_npm:
    docker:
      - image: node:8
        user: node
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm install
      - run: npm publish
