version: 2

workflows:
  version: 2
  tests:
    jobs:
      - test:
        requires:
          - node4
          - node6
          - node8

jobs:
  node4:
    docker:
      - image: node:4
    <<: *test
  node6:
    docker:
      - image: node:6
    <<: *test
  node8:
    docker:
      - image: node:8
    <<: *test

test: &test
  steps:
    - checkout
    - run:
        name: Install
        command: npm install
    - run:
        name: Test
        command: npm test