version: 2

workflows:
  tests:
    jobs:
      - tests
        requires:
          - node4
          - node6
          - node8

jobs:
  node4:
    docker:
      - image: node:4
    <<: *tests
  node6:
    docker:
      - image: node:6
    <<: *tests
  node8:
    docker:
      - image: node:8
    <<: *tests

tests: &tests
  steps:
    - checkout
    - run:
        name: Install
        command: npm install
    - run:
        name: Test
        command: npm test