version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Install protoc
          command: |
            apt-get update
            apt-get install protobuf-compiler
      - run:
          name: Run tests
          command: |
            npm install
            npm test
workflows:
  version: 2
  tests:
    jobs:
      - build
      - test:
          requires:
            - build
