createTime: '2025-10-20T21:38:12.742722302Z'
description: Presubmit build with node 18
filename: ci/cloudbuild_with_credentials.yaml
github:
  name: google-cloud-node-core
  owner: googleapis
  pullRequest:
    branch: ^main$
    commentControl: COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY
id: cd0eedc4-7379-4d88-9a34-ce1f5190d709
includeBuildLogs: INCLUDE_BUILD_LOGS_WITH_STATUS
name: gcnc-samples-presubmit-node-with-credentials
resourceName: projects/long-door-651/locations/global/triggers/cd0eedc4-7379-4d88-9a34-ce1f5190d709
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: presubmit
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: samples