createTime: '2025-09-18T18:59:45.514768458Z'
description: Nightly build with node 18
gitFileSource:
  path: ci/cloudbuild.yaml
  repoType: GITHUB
  revision: refs/heads/main
  uri: https://github.com/googleapis/google-cloud-node-core
id: 51a3532e-42b5-452f-acd5-b286fd57cd1d
name: gcnc-system-nightly-node
resourceName: projects/long-door-651/locations/global/triggers/51a3532e-42b5-452f-acd5-b286fd57cd1d
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
sourceToBuild:
  ref: refs/heads/main
  repoType: GITHUB
  uri: https://github.com/googleapis/google-cloud-node-core
substitutions:
  _BUILD_TYPE: nightly
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: system
