createTime: '2025-09-18T18:59:48.419617959Z'
description: Continuous build with node
filename: ci/gcnc-cloudbuild.yaml
github:
  name: google-cloud-node-core
  owner: googleapis
  push:
    branch: ^main$
id: 6d4bac54-3cc5-4178-af9e-a0e220dfe95e
name: gcnc-samples-continuous-node
resourceName: projects/long-door-651/locations/global/triggers/6d4bac54-3cc5-4178-af9e-a0e220dfe95e
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: continuous
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: samples
