createTime: '2025-09-18T18:59:44.053456230Z'
description: Continuous build with node 18
filename: ci/cloudbuild.yaml
github:
  name: google-cloud-node-core
  owner: googleapis
  push:
    branch: ^main$
id: e0dc1c0a-aac4-49c0-ba4c-78fdafdea75e
name: gcnc-system-continuous-node
resourceName: projects/long-door-651/locations/global/triggers/e0dc1c0a-aac4-49c0-ba4c-78fdafdea75e
serviceAccount: projects/long-door-651/serviceAccounts/kokoro-system-test@long-door-651.iam.gserviceaccount.com
substitutions:
  _BUILD_TYPE: continuous
  _LOGS_BUCKET: cloud-node-public-logs
  _TEST_TYPE: system
