container:
  image: node:10

lint_task:
  install_script: npm install
  test_script: npm run lint

system_test_task:
  install_script: npm install
  test_script: npm run system-test

browser_test_task:
  container:
    image: gmathieu/node-browsers
    # the most popular image on Dockerhub with both node8, chromium, and
    # all required dependencies
  install_script: npm install
  test_script: npm run browser-test

test_task:
  container:
    matrix:
      image: node:11
      image: node:10
      image: node:8
      image: node:6
  install_script: npm install
  test_script: npm test

coverage_task:
  env:
    CODECOV_TOKEN: ENCRYPTED[750eb3c966bdd3472a953856902500c28d7785af18131d3045650172d4351bf91617be1f2b4a913a423f5d6fb21a11b8]
  script:
    - npm install
    - npm test
    - npm run codecov

publish_task:
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - test_task
    - lint_task
  environment:
    GITHUB_TOKEN: ENCRYPTED[8d2c18c6edadfd1ad0ebccb041ea7500081faea2824d499aa3b2882505fbbdbfd97490f499ad5e973db974a38d92d531]
    NPM_TOKEN: ENCRYPTED[845742743a538e14424940f88bbcdc3e4cdb18bf6ec362dad2509c06c9fb20db3a1820e04e7fcc061fc58ddd4dbf5d4a]
  script:
    - npm install
    - npm run compile
    - npx semantic-release
