on:
  push:
    branches:
      - main
    pull_request:
name: continuous
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: ^10.0.0
      - run: node --version
      - run: ci/run_conditional_tests.sh
        name: Run unit tests
        env:
          BUILD_TYPE: continuous
          TEST_TYPE: units
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: node --version
      - run: ci/run_conditional_tests.sh
        env:
          MOCHA_THROW_DEPRECATION: false
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 300 # Fetch all history for comparison
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: ci/run_conditional_tests.sh
        name: Run lint
        env:
          BUILD_TYPE: continuous
          TEST_TYPE: lint
