name: invalid_link
on:
  issues:
    types: [opened, reopened]

jobs:
  close:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: pnpm/action-setup@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
        working-directory: ./.github/scripts
      - uses: actions/github-script@v8
        with:
          script: |
            const script = require('./.github/scripts/close-invalid-link.cjs')
            await script({github, context})
