on:
  pull_request:
name: presubmit
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 300
      - uses: pnpm/action-setup@v4
        with:
          version: ^10.0.0
      - run: node --version
      - run: npm i && ci/run_conditional_tests.sh
        name: Run unit tests
        env:
          BUILD_TYPE: presubmit
          TEST_TYPE: units
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 300 # Fetch all history for comparison
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm i && ci/run_conditional_tests.sh
        name: Run lint
        env:
          BUILD_TYPE: presubmit
          TEST_TYPE: lint
