on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  update-api-list:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: googleapis/code-suggester@v5
        env:
          ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
        with:
          command: pr
          force: true
          upstream_owner: googleapis
          upstream_repo: google-cloud-node-core
          description: 'Update the list of available APIs in the README.'
          title: 'docs: update the list of available APIs'
          message: 'docs: update the list of available APIs'
          branch: update-api-list
          git_dir: '.'
